build:
  image: rics3n/angular:latest
  commands:
    - npm config set cache /tmp/npm --global
    - npm install --cache /tmp/npm && bower install --allow-root --config.storage.packages=/tmp/bower
    - gulp build

publish:
  docker:
    image: rics3n/drone-docker
    registry: $$DOCKER_HUB
    repo: $$DOCKER_HUB/angular_app
    username: $$DOCKER_PRIVATE_USERNAME
    password: $$DOCKER_PRIVATE_PW
    email: $$DOCKER_PRIVATE_EMAIL
    insecure: true
