build:
  image: rics3n/angular:latest
  commands:
    - npm config set cache /tmp/npm --global

publish:
  rics3_docker:
    registry: $$DOCKER_HUB
    repo: $$DOCKER_HUB/angular_app
    username: $$DOCKER_PRIVATE_USERNAME
    password: $$DOCKER_PRIVATE_PW
    email: $$DOCKER_PRIVATE_EMAIL
    insecure: true
