build:
  image: rics3n/angular:latest
  commands:
    - npm config set cache /tmp/npm --global
    - npm install --cache /tmp/npm && bower install --allow-root --config.storage.packages=/tmp/bower
    - gulp build
