build:
  image: rics3n/angular:latest
  commands:
    - npm config set cache /tmp/npm --global
    - npm install --cache /tmp/npm && bower install --allow-root --config.storage.packages=/tmp/bower
    - gulp build

cache:
  mount:
    - node_modules
    - .git
    - /tmp/npm
    - /tmp/bower

publish:
  docker:
    registry: $$DOCKER_HUB
    repo: $$DOCKER_HUB/angular_app
    username: $$DOCKER_PRIVATE_USERNAME
    password: $$DOCKER_PRIVATE_PW
    email: $$DOCKER_PRIVATE_EMAIL
