build:
  image: rics3n/angular:latest
  commands:
    - npm install && bower install --allow-root
    - gulp build

cache:
  mount:
    - node_modules
    - .git
    - bower_components

publish:
  docker:
    registry: $$DOCKER_HUB
    repo: $$DOCKER_HUB/angular-app
    username: $$DOCKER_PRIVATE_USERNAME
    password: $$DOCKER_PRIVATE_PW
    email: $$DOCKER_PRIVATE_EMAIL
    tag: 
      - $$BRANCH_$$COMMIT
    insecure: true
    when:
      branch: stage

  docker:
    registry: $$DOCKER_HUB
    repo: $$DOCKER_HUB/angular_app
    username: $$DOCKER_PRIVATE_USERNAME
    password: $$DOCKER_PRIVATE_PW
    email: $$DOCKER_PRIVATE_EMAIL
    insecure: true
    tag: 
      - $$COMMIT
      - latest
    when:
      branch: master