build:
  image: rics3n/angular:latest
  commands:
    - npm config set cache .npm --global
    - npm install --cache .npm && bower install --allow-root --config.storage.packages=.bower
    - gulp build

cache:
  mount:
    - node_modules
    - .git
    - bower_components
    - .bower
    - .npm

publish:
  rics3n_docker:
    image: rics3n/drone-docker:latest
    privileged: true
    registry: $$DOCKER_HUB
    repo: $$DOCKER_HUB/angular_app
    username: $$DOCKER_PRIVATE_USERNAME
    password: $$DOCKER_PRIVATE_PW
    email: $$DOCKER_PRIVATE_EMAIL
    insecure: true
