build:
  image: rics3n/angular:latest
  commands:
    - npm install && bower install --allow-root
    - gulp build

cache:
  mount:
    - node_modules
    - .git
    - bower_components

publish:
  rics3n_docker:
    image: rics3n/drone-docker:latest
    privileged: true
    registry: $$DOCKER_HUB
    repo: $$DOCKER_HUB/angular_app
    username: $$DOCKER_PRIVATE_USERNAME
    password: $$DOCKER_PRIVATE_PW
    email: $$DOCKER_PRIVATE_EMAIL
    tag: stage_$(git rev-parse --short HEAD)
    when:
      branch: stage

  rics3n_docker:
    image: rics3n/drone-docker:latest
    privileged: true
    registry: $$DOCKER_HUB
    repo: $$DOCKER_HUB/angular_app
    username: $$DOCKER_PRIVATE_USERNAME
    password: $$DOCKER_PRIVATE_PW
    email: $$DOCKER_PRIVATE_EMAIL
    when:
      branch: master